version: 2

jobs:
  build:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - restore_cache:
          key: yarn-cache-{{ .Branch }}
      - restore_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
      - run:
          name: Install dependencies
          command: yarn --frozen-lockfile
      - save_cache:
          key: yarn-cache-{{ .Branch }}
          paths:
            - ~/.cache/yarn
      - save_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules
      - run:
          name: Build
          command: yarn build
      - run:
          name: Test
          command: ./.circleci/test.sh
